---
- hosts: localhost
  connection: local
  tasks:
    - name: "Install pip"
      easy_install:
        name: pip
        state: present

    - name: "Yum install"
      yum:
        name: "{{ item }}"
      with_items:
        - gcc
        - openssl-devel
        - python2-devel

    - name: "pip install"
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - boto
        - ansible